/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MovieDetail: typeof import('./src/components/Detail/MovieDetail.vue')['default']
    MovieItem: typeof import('./src/components/Movie/MovieItem.vue')['default']
    MovieList: typeof import('./src/components/Movie/MovieList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
